import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class AppLocaleController extends ChangeNotifier {
  AppLocaleController._();

  static final instance = AppLocaleController._();
  static const _preferenceKey = 'app_language';

  Locale _locale = const Locale('en');

  Locale get locale => _locale;
  bool get isVietnamese => _locale.languageCode == 'vi';

  Future<void> load() async {
    final preferences = await SharedPreferences.getInstance();
    _locale = Locale(preferences.getString(_preferenceKey) ?? 'en');
  }

  Future<void> setLanguage(String languageCode) async {
    if (_locale.languageCode == languageCode) return;
    _locale = Locale(languageCode);
    notifyListeners();
    final preferences = await SharedPreferences.getInstance();
    await preferences.setString(_preferenceKey, languageCode);
  }
}

class AppLanguageScope extends InheritedNotifier<AppLocaleController> {
  AppLanguageScope({super.key, required super.child})
    : super(notifier: AppLocaleController.instance);

  static AppLocaleController of(BuildContext context) {
    return context
        .dependOnInheritedWidgetOfExactType<AppLanguageScope>()!
        .notifier!;
  }
}

abstract final class AppText {
  static const Map<String, Map<String, String>> _values = {
    'en': {
      'settings': 'Settings',
      'language': 'Language',
      'languageSubtitle': 'Choose the language used in the app',
      'english': 'English',
      'vietnamese': 'Vietnamese',
      'myAccount': 'My account',
      'myOrders': 'My orders',
      'myOrdersSubtitle': 'Track, return or buy again',
      'returnsRefunds': 'Returns & refunds',
      'returnsRefundsSubtitle': 'Track return requests and refunds',
      'wishlist': 'Wishlist',
      'wishlistSubtitle': 'Your saved products',
      'addresses': 'Addresses',
      'addressesSubtitle': 'Manage delivery addresses',
      'changePassword': 'Change password',
      'changePasswordSubtitle': 'Update your account password',
      'helpSupport': 'Help & support',
      'helpSupportSubtitle': 'Returns, payments and contact',
      'helpQuickActions': 'Quick actions',
      'helpTopics': 'Help topics',
      'helpOrdersSubtitle': 'View order status, payment and shipment details.',
      'helpReturnsSubtitle': 'Track submitted return and refund requests.',
      'helpPaymentTitle': 'Payments',
      'helpPaymentBody': 'You can pay by COD, VNPAY, PayPal or SePay.',
      'helpShippingTitle': 'Shipping',
      'helpShippingBody':
          'After payment, your order moves to processing and shipment tracking will be available when the admin creates a shipment.',
      'helpReturnTitle': 'Returns and refunds',
      'helpReturnBody':
          'Open an eligible order detail to submit a return request. You can follow approval and refund status in Returns & refunds.',
      'helpAccountTitle': 'Account and OTP',
      'helpAccountBody':
          'Password reset OTP emails are sent from Adidas Shoes Store and expire after 5 minutes. Check spam if you cannot find the email.',
      'helpEmailTitle': 'Email sender',
      'helpEmailBody':
          'Emails are displayed as Adidas Shoes Store. A real Adidas domain mailbox can be connected later through SMTP settings.',
      'contactSupport': 'Contact support',
      'emailSupport': 'Email support',
      'hotlineSupport': 'Hotline',
      'signOut': 'Sign out',
      'forgotPassword': 'Forgot password?',
      'welcomeBack': 'Welcome\nback.',
      'signInSubtitle':
          'Sign in to access your bag, wishlist and member rewards.',
      'password': 'Password',
      'signIn': 'Sign in',
      'or': 'Or',
      'continueWithGoogle': 'Continue with Google',
      'notMember': 'Not a member?',
      'joinNow': 'Join now',
      'forgotPasswordTitle': 'Forgot password',
      'checkEmail': 'Check your\nemail.',
      'otpDescription':
          'We will send a 6-digit verification code to the email you enter.',
      'emailAddress': 'Email address',
      'sendOtp': 'Send OTP',
      'sending': 'Sending...',
      'otpSent': 'OTP was sent to',
      'resetPassword': 'Reset password',
      'verifyReset': 'Verify and\nreset.',
      'otpSentDescription': 'Enter the 6-digit OTP sent to',
      'otpExpires': 'It expires in 5 minutes.',
      'otpLabel': '6-digit OTP',
      'newPassword': 'New password',
      'confirmNewPassword': 'Confirm new password',
      'resetting': 'Resetting...',
      'resendOtp': 'Resend OTP',
      'otpResent': 'A new OTP has been sent.',
      'passwordResetSuccess': 'Password reset successfully.',
      'currentPassword': 'Current password',
      'changePasswordHeading': 'Secure your\naccount.',
      'passwordHint': 'Choose a new password with at least 6 characters.',
      'updating': 'Updating...',
      'passwordChanged': 'Password changed successfully.',
      'passwordLengthError': 'Password must contain at least 6 characters.',
      'passwordMismatch': 'New passwords do not match.',
      'myAddresses': 'My addresses',
      'addAddress': 'Add address',
      'editAddress': 'Edit address',
      'newDeliveryAddress': 'New delivery\naddress.',
      'updateAddress': 'Update your\naddress.',
      'saveAddress': 'Save address',
      'saving': 'Saving...',
      'defaultLabel': 'Default',
      'setDefault': 'Set default',
      'edit': 'Edit',
      'delete': 'Delete',
      'cancel': 'Cancel',
      'confirm': 'Confirm',
      'noAddresses': 'No saved addresses',
      'noAddressesSubtitle': 'Add a delivery address to make checkout faster.',
      'addFirstAddress': 'Add your first address',
      'receiverName': 'Receiver name',
      'phoneNumber': 'Phone number',
      'streetAddress': 'Street address',
      'ward': 'Ward',
      'district': 'District',
      'cityProvince': 'City / Province',
      'setDefaultAddress': 'Set as default address',
      'setDefaultAddressSubtitle':
          'This address will be selected first at checkout.',
      'requiredField': 'Required field',
      'invalidEmail': 'Enter a valid email address.',
      'invalidPhone': 'Enter a valid phone number',
      'deleteAddressQuestion': 'Delete address?',
      'retry': 'Retry',
      'notAvailable': 'N/A',
      'statusPendingPayment': 'Pending payment',
      'statusPaid': 'Paid',
      'statusProcessing': 'Processing',
      'statusShipping': 'Shipping',
      'statusDelivered': 'Delivered',
      'statusCancelled': 'Cancelled',
      'statusCompleted': 'Completed',
      'home': 'Home',
      'shop': 'Shop',
      'aiStylist': 'AI Stylist',
      'profile': 'Profile',
      'editProfile': 'Edit profile',
      'saveProfile': 'Save profile',
      'profileUpdated': 'Profile updated successfully',
      'emailCannotBeChanged': 'Sign-in email cannot be changed',
      'paymentMethods': 'Payment methods',
      'paymentMethodsSubtitle': 'COD, VNPAY, PayPal and SePay options',
      'codDescription': 'Pay in cash when your order is delivered.',
      'vnpayDescription': 'Pay online through the VNPay payment gateway.',
      'gender': 'Gender',
      'male': 'Male',
      'female': 'Female',
      'other': 'Other',
      'selectDateOfBirth': 'Select date of birth',
      'fullNameRequired': 'Enter your full name',
      'signInToContinue': 'Sign in to access your account features.',
      'register': 'Register',
      'adiclubMember': 'Adiclub member',
      'signInToSync': 'Sign in to sync your account',
      'adminTools': 'Admin tools',
      'adminDashboard': 'Admin dashboard',
      'businessOverview': 'Business overview',
      'metricRevenue': 'Revenue',
      'metricOrders': 'Orders',
      'metricProducts': 'Products',
      'metricCustomers': 'Customers',
      'metricPending': 'Pending',
      'metricReturns': 'Returns',
      'adminOrderSearchHint': 'Order code, customer or email',
      'adminNoOrders': 'No orders found.',
      'unpaid': 'Unpaid',
      'update': 'Update',
      'updateOrderStatus': 'Update order status',
      'customer': 'Customer',
      'userManagement': 'User management',
      'userManagementSubtitle': 'View and lock user accounts',
      'userSearchHint': 'Name, email or phone',
      'noUsersFound': 'No users found',
      'adminRole': 'Admin',
      'customerRole': 'Customer',
      'orderManagement': 'Order management',
      'orderManagementSubtitle': 'Review and update all orders',
      'productManagement': 'Product management',
      'productInventory': 'Products & inventory',
      'catalogInventory': 'Catalog and inventory',
      'deleteProduct': 'Delete product',
      'deleteProductQuestion': 'Are you sure you want to delete',
      'productDeleted': 'Product deleted successfully',
      'noCategory': 'No category',
      'active': 'Active',
      'inactive': 'Inactive',
      'manageImages': 'Manage images',
      'manageVariants': 'Manage variants',
      'editProduct': 'Edit product',
      'createProduct': 'Create product',
      'updateProduct': 'Update product',
      'productName': 'Product name',
      'basePrice': 'Base price',
      'brand': 'Brand',
      'material': 'Material',
      'productCreated': 'Product created successfully',
      'productUpdated': 'Product updated successfully',
      'failedLoadCategories': 'Failed to load categories',
      'invalidBasePrice': 'Base price must be a valid number',
      'categoryManagement': 'Category management',
      'approveReturns': 'Approve returns and complete refunds',
      'approveReturn': 'Approve return',
      'rejectReturn': 'Reject return',
      'completeRefundTransactionCode': 'Complete refund: transaction code',
      'returnRequests': 'Return requests',
      'refunds': 'Refunds',
      'returnRequest': 'Return request',
      'refund': 'Refund',
      'reject': 'Reject',
      'approve': 'Approve',
      'complete': 'Complete',
      'refundsEmpty': 'No refunds yet.',
      'shipments': 'Shipments',
      'shipment': 'Shipment',
      'noShipmentsFound': 'No shipments found',
      'searchShipments': 'Search shipments...',
      'adminAccessRequired': 'Admin access required',
      'shipmentDetail': 'Shipment detail',
      'shipmentIdMissing': 'Shipment ID is missing',
      'shipmentNotFound': 'Shipment not found',
      'noNextStatus': 'No valid next statuses',
      'noteOptional': 'Note (optional)',
      'shipmentStatusUpdated': 'Shipment status updated to',
      'orderInfo': 'Order info',
      'customerInfo': 'Customer info',
      'transactionCode': 'Transaction code',
      'orderItems': 'Order items',
      'noOrderItems': 'No order items returned',
      'updateTrackingInfo': 'Update tracking info',
      'updateShipmentStatus': 'Update shipment status',
      'shipmentManagement': 'Shipment management',
      'shipmentManagementSubtitle': 'Create and track shipments',
      'deleteCategory': 'Delete category',
      'deleteCategoryQuestion': 'Are you sure you want to delete',
      'categoryDeleted': 'Category deleted successfully',
      'editCategory': 'Edit category',
      'createCategory': 'Create category',
      'updateCategory': 'Update category',
      'categoryName': 'Category name',
      'categoryCreated': 'Category created successfully',
      'categoryUpdated': 'Category updated successfully',
      'categoryNameTooLong': 'Category name must be less than 100 characters',
      'descriptionTooLong': 'Description must be less than 255 characters',
      'createShipment': 'Create shipment',
      'shipmentSaved': 'Shipment saved successfully',
      'trackingUpdated': 'Tracking info updated successfully',
      'orderId': 'Order ID',
      'orderIdRequired': 'Order ID is required',
      'carrierRequired': 'Carrier is required',
      'trackingNumberRequired': 'Tracking number is required',
      'optionalDateFormat': 'Optional, format: YYYY-MM-DD',
      'saveChanges': 'Save changes',
      'newSeason': 'New season / 2026',
      'heroTitle': 'You got\nthis.',
      'heroSubtitle':
          'Own every move with footwear built for sport, streets and everything between.',
      'shopNow': 'Shop now',
      'shopBySport': 'Shop by sport',
      'viewAll': 'View all',
      'trendingNow': 'Trending now',
      'shopAll': 'Shop all',
      'noProducts': 'No products available',
      'joinTheClub': 'Join the club',
      'memberBenefits': 'Members get rewards, drops and free delivery.',
      'becomeMember': 'Become a\nmember.',
      'registerSubtitle':
          'Create your account and unlock members-only products, rewards and experiences.',
      'fullName': 'Full name',
      'phoneOptional': 'Phone number (optional)',
      'acceptTerms': 'I agree to the membership terms and privacy policy.',
      'creating': 'Creating...',
      'createAccount': 'Create account',
      'alreadyMember': 'Already a member? Sign in',
      'registerValidation':
          'Enter your name, email and a 6+ character password.',
      'categories': 'Categories',
      'noCategories': 'No categories found',
      'noDescription': 'No description',
      'selectCategory': 'Select a category to view products',
      'noProductsIn': 'No products in',
      'error': 'Error',
      'myCart': 'My cart',
      'clearCart': 'Clear cart',
      'clearCartQuestion': 'Remove all items from your cart?',
      'clear': 'Clear',
      'cartEmpty': 'Your cart is empty',
      'total': 'Total',
      'checkout': 'Checkout',
      'myWishlist': 'My wishlist',
      'clearWishlist': 'Clear wishlist',
      'clearWishlistQuestion': 'Remove all items from your wishlist?',
      'wishlistEmpty': 'Your wishlist is empty',
      'all': 'All',
      'searchHint': 'Search shoes, collections, sport...',
      'noProductsFound': 'No products found',
      'productDetails': 'Product details',
      'noVariants': 'No variants available',
      'selectSizeColor': 'Select size & color',
      'selectSizeColorPrompt': 'Please select size and color',
      'addedToCart': 'Added to cart',
      'addedToWishlist': 'Added to wishlist',
      'items': 'items',
      'customerReviews': 'Customer reviews',
      'writeReview': 'Write a review',
      'editReview': 'Edit review',
      'reviewLocked': 'Reviewed',
      'noReviews': 'No reviews yet. Be the first to share your experience.',
      'reviewSubmitted': 'Review submitted',
      'relatedProducts': 'Related products',
      'stock': 'Stock',
      'productDescription': 'Product description',
      'productColor': 'Color',
      'productSize': 'Size',
      'addToBag': 'Add to bag',
      'buyNow': 'Buy now',
      'adding': 'Adding...',
      'shippingAddress': 'Shipping address',
      'selectAddress': 'Select address',
      'changeAddress': 'Change',
      'selectShippingAddress': 'Please select a shipping address',
      'orderCreated': 'Order created successfully',
      'addShippingAddress': 'Add a shipping address',
      'paymentMethod': 'Payment method',
      'note': 'Note',
      'placeOrder': 'Place order',
      'vnpayUnavailable': 'VNPay integration is not available yet',
      'cannotOpenVnpay': 'Could not open VNPay payment page',
      'orderCode': 'Order code',
      'orderStatus': 'Status',
      'payment': 'Payment',
      'createdAt': 'Created',
      'orderDetail': 'Order detail',
      'receiver': 'Receiver',
      'name': 'Name',
      'address': 'Address',
      'quantity': 'Quantity',
      'unitPrice': 'Unit',
      'shipping': 'Shipping',
      'shipmentUnavailable': 'Shipment information is not available yet.',
      'trackShipment': 'Track shipment',
      'shipmentStatus': 'Shipment status',
      'carrier': 'Carrier',
      'trackingNumber': 'Tracking number',
      'estimatedDelivery': 'Estimated delivery',
      'shippedAt': 'Shipped at',
      'deliveredAt': 'Delivered at',
      'receiverPhone': 'Receiver phone',
      'paymentStatus': 'Payment status',
      'paidAt': 'Paid at',
      'totals': 'Totals',
      'totalAmount': 'Total amount',
      'shippingFee': 'Shipping fee',
      'discount': 'Discount',
      'finalAmount': 'Final amount',
      'refreshPaymentStatus': 'Refresh payment status',
      'requestReturn': 'Request a return',
      'cancelOrder': 'Cancel order',
      'cancelOrderQuestion': 'Cancel order',
      'orderCancelled': 'Order cancelled successfully',
      'confirmReceived': 'Received order',
      'confirmReceivedMessage':
          'Confirm that you have received this order and want to complete it?',
      'orderCompleted':
          'Order completed. You can now review purchased products.',
      'shipmentFallback':
          'Shipment details are not available yet. You can still follow the order progress below.',
      'paymentStatusRefreshed': 'Payment status refreshed',
      'orderIdMissing': 'Order ID is missing',
      'orderNotFound': 'Order not found',
      'goToLogin': 'Go to login',
      'noOrdersYet': 'No orders yet',
      'returnWholeOrder': 'Return whole order',
      'openReturnFromOrder': 'Open this screen from an order detail.',
      'returnReason': 'Reason for return',
      'returnReasonDefective': 'Defective item',
      'returnReasonWrongDescription': 'Item does not match description',
      'returnReasonWrongItem': 'Wrong item delivered',
      'returnReasonMissingItem': 'Missing item/accessory',
      'returnReasonDamagedPackage': 'Damaged package',
      'returnReasonChangedMind': 'No longer needed',
      'returnReasonOther': 'Other reason',
      'returnDetails': 'Details',
      'returnDetailsOptional': 'Additional details (optional)',
      'returnEvidence': 'Evidence image/video',
      'returnEvidenceHint': 'Upload photos or videos as evidence',
      'choosePhotos': 'Choose photos',
      'takePhoto': 'Take photo',
      'chooseVideo': 'Choose video',
      'selectReturnReasonPrompt': 'Please select a return reason.',
      'returnSubmitted': 'Return request submitted.',
      'submitReturnRequest': 'Submit return request',
      'submitting': 'Submitting...',
      'trackingProgress': 'Tracking progress',
      'order': 'Order',
      'amount': 'Amount',
      'paymentResultHint':
          'After payment, return to app and refresh payment status.',
      'paymentCompleted': 'Payment completed successfully.',
      'viewOrderDetail': 'View order detail',
      'returnsRefundsEmpty': 'No return requests yet.',
      'adminNote': 'Admin note',
      'statusPending': 'Pending',
      'statusApproved': 'Approved',
      'statusRefunded': 'Refunded',
      'statusRejected': 'Rejected',
      'statusPreparing': 'Preparing',
      'statusShipped': 'Shipped',
      'statusInTransit': 'In transit',
      'statusOutForDelivery': 'Out for delivery',
      'statusFailed': 'Failed',
      'statusReturned': 'Returned',
    },
    'vi': {
      'settings': 'Cài đặt',
      'language': 'Ngôn ngữ',
      'languageSubtitle': 'Chọn ngôn ngữ hiển thị trong ứng dụng',
      'english': 'Tiếng Anh',
      'vietnamese': 'Tiếng Việt',
      'myAccount': 'Tài khoản của tôi',
      'myOrders': 'Đơn hàng của tôi',
      'myOrdersSubtitle': 'Theo dõi, hoàn trả hoặc mua lại',
      'returnsRefunds': 'Trả hàng & hoàn tiền',
      'returnsRefundsSubtitle': 'Theo dõi yêu cầu trả hàng và hoàn tiền',
      'wishlist': 'Danh sách yêu thích',
      'wishlistSubtitle': 'Các sản phẩm bạn đã lưu',
      'addresses': 'Địa chỉ',
      'addressesSubtitle': 'Quản lý địa chỉ giao hàng',
      'changePassword': 'Đổi mật khẩu',
      'changePasswordSubtitle': 'Cập nhật mật khẩu tài khoản',
      'helpSupport': 'Trợ giúp & hỗ trợ',
      'helpSupportSubtitle': 'Trả hàng, thanh toán và liên hệ',
      'helpQuickActions': 'Thao tác nhanh',
      'helpTopics': 'Chủ đề hỗ trợ',
      'helpOrdersSubtitle':
          'Xem trạng thái đơn hàng, thanh toán và vận chuyển.',
      'helpReturnsSubtitle': 'Theo dõi yêu cầu trả hàng và hoàn tiền đã gửi.',
      'helpPaymentTitle': 'Thanh toán',
      'helpPaymentBody':
          'Bạn có thể thanh toán bằng COD, VNPAY, PayPal hoặc SePay.',
      'helpShippingTitle': 'Vận chuyển',
      'helpShippingBody':
          'Sau khi thanh toán, đơn hàng chuyển sang xử lý và thông tin vận chuyển sẽ có khi quản trị viên tạo đơn giao hàng.',
      'helpReturnTitle': 'Trả hàng và hoàn tiền',
      'helpReturnBody':
          'Mở chi tiết đơn hàng đủ điều kiện để gửi yêu cầu trả hàng. Bạn có thể theo dõi trạng thái duyệt và hoàn tiền trong Trả hàng & hoàn tiền.',
      'helpAccountTitle': 'Tài khoản và OTP',
      'helpAccountBody':
          'Email OTP đặt lại mật khẩu được gửi từ Adidas Shoes Store và hết hạn sau 5 phút. Hãy kiểm tra thư rác nếu bạn không thấy email.',
      'helpEmailTitle': 'Người gửi email',
      'helpEmailBody':
          'Email hiển thị tên Adidas Shoes Store. Có thể kết nối mailbox tên miền Adidas thật sau thông qua cấu hình SMTP.',
      'contactSupport': 'Liên hệ hỗ trợ',
      'emailSupport': 'Email hỗ trợ',
      'hotlineSupport': 'Hotline',
      'signOut': 'Đăng xuất',
      'forgotPassword': 'Quên mật khẩu?',
      'welcomeBack': 'Chào mừng\ntrở lại.',
      'signInSubtitle':
          'Đăng nhập để truy cập giỏ hàng, yêu thích và phần thưởng.',
      'password': 'Mật khẩu',
      'signIn': 'Đăng nhập',
      'or': 'Hoặc',
      'continueWithGoogle': 'Tiếp tục với Google',
      'notMember': 'Chưa có tài khoản?',
      'joinNow': 'Đăng ký ngay',
      'forgotPasswordTitle': 'Quên mật khẩu',
      'checkEmail': 'Kiểm tra\nemail.',
      'otpDescription': 'Chúng tôi sẽ gửi mã OTP 6 số tới email bạn nhập.',
      'emailAddress': 'Địa chỉ email',
      'sendOtp': 'Gửi OTP',
      'sending': 'Đang gửi...',
      'otpSent': 'OTP đã được gửi tới',
      'resetPassword': 'Đặt lại mật khẩu',
      'verifyReset': 'Xác thực và\nđặt lại.',
      'otpSentDescription': 'Nhập mã OTP 6 số đã gửi tới',
      'otpExpires': 'Mã hết hạn sau 5 phút.',
      'otpLabel': 'OTP 6 số',
      'newPassword': 'Mật khẩu mới',
      'confirmNewPassword': 'Xác nhận mật khẩu mới',
      'resetting': 'Đang đặt lại...',
      'resendOtp': 'Gửi lại OTP',
      'otpResent': 'OTP mới đã được gửi.',
      'passwordResetSuccess': 'Đặt lại mật khẩu thành công.',
      'currentPassword': 'Mật khẩu hiện tại',
      'changePasswordHeading': 'Bảo vệ\ntài khoản.',
      'passwordHint': 'Chọn mật khẩu mới có ít nhất 6 ký tự.',
      'updating': 'Đang cập nhật...',
      'passwordChanged': 'Đổi mật khẩu thành công.',
      'passwordLengthError': 'Mật khẩu phải có ít nhất 6 ký tự.',
      'passwordMismatch': 'Mật khẩu mới không khớp.',
      'myAddresses': 'Địa chỉ của tôi',
      'addAddress': 'Thêm địa chỉ',
      'editAddress': 'Sửa địa chỉ',
      'newDeliveryAddress': 'Địa chỉ giao\nhàng mới.',
      'updateAddress': 'Cập nhật\nđịa chỉ.',
      'saveAddress': 'Lưu địa chỉ',
      'saving': 'Đang lưu...',
      'defaultLabel': 'Mặc định',
      'setDefault': 'Đặt mặc định',
      'edit': 'Sửa',
      'delete': 'Xóa',
      'cancel': 'Hủy',
      'confirm': 'Xác nhận',
      'noAddresses': 'Chưa có địa chỉ',
      'noAddressesSubtitle': 'Thêm địa chỉ giao hàng để thanh toán nhanh hơn.',
      'addFirstAddress': 'Thêm địa chỉ đầu tiên',
      'receiverName': 'Tên người nhận',
      'phoneNumber': 'Số điện thoại',
      'streetAddress': 'Địa chỉ đường',
      'ward': 'Phường / Xã',
      'district': 'Quận / Huyện',
      'cityProvince': 'Tỉnh / Thành phố',
      'setDefaultAddress': 'Đặt làm địa chỉ mặc định',
      'setDefaultAddressSubtitle':
          'Địa chỉ này sẽ được chọn trước khi thanh toán.',
      'requiredField': 'Trường bắt buộc',
      'invalidEmail': 'Vui lòng nhập email hợp lệ.',
      'invalidPhone': 'Vui lòng nhập số điện thoại hợp lệ',
      'deleteAddressQuestion': 'Xóa địa chỉ?',
      'retry': 'Thử lại',
      'notAvailable': 'Không có',
      'statusPendingPayment': 'Chờ thanh toán',
      'statusPaid': 'Đã thanh toán',
      'statusProcessing': 'Đang xử lý',
      'statusShipping': 'Đang giao',
      'statusDelivered': 'Đã giao',
      'statusCancelled': 'Đã hủy',
      'statusCompleted': 'Hoàn tất',
      'home': 'Trang chủ',
      'shop': 'Cửa hàng',
      'aiStylist': 'Trợ lý AI',
      'profile': 'Tài khoản',
      'editProfile': 'Chỉnh sửa hồ sơ',
      'saveProfile': 'Lưu hồ sơ',
      'profileUpdated': 'Cập nhật hồ sơ thành công',
      'emailCannotBeChanged': 'Email đăng nhập không thể thay đổi',
      'paymentMethods': 'Phương thức thanh toán',
      'paymentMethodsSubtitle': 'COD, VNPAY, PayPal và SePay',
      'codDescription': 'Thanh toán bằng tiền mặt khi nhận hàng.',
      'vnpayDescription': 'Thanh toán trực tuyến qua cổng VNPAY.',
      'gender': 'Giới tính',
      'male': 'Nam',
      'female': 'Nữ',
      'other': 'Khác',
      'selectDateOfBirth': 'Chọn ngày sinh',
      'fullNameRequired': 'Vui lòng nhập họ và tên',
      'signInToContinue': 'Đăng nhập để sử dụng các chức năng tài khoản.',
      'register': 'Đăng ký',
      'adiclubMember': 'Thành viên Adiclub',
      'signInToSync': 'Đăng nhập để đồng bộ tài khoản',
      'adminTools': 'Công cụ quản trị',
      'adminDashboard': 'Bảng điều khiển quản trị',
      'businessOverview': 'Tổng quan hoạt động kinh doanh',
      'metricRevenue': 'Doanh thu',
      'metricOrders': 'Đơn hàng',
      'metricProducts': 'Sản phẩm',
      'metricCustomers': 'Khách hàng',
      'metricPending': 'Chờ xử lý',
      'metricReturns': 'Trả hàng',
      'adminOrderSearchHint': 'Mã đơn, khách hàng hoặc email',
      'adminNoOrders': 'Không tìm thấy đơn hàng.',
      'unpaid': 'Chưa thanh toán',
      'update': 'Cập nhật',
      'updateOrderStatus': 'Cập nhật trạng thái đơn hàng',
      'customer': 'Khách hàng',
      'userManagement': 'Quản lý người dùng',
      'userManagementSubtitle': 'Xem và khóa tài khoản người dùng',
      'userSearchHint': 'Tên, email hoặc số điện thoại',
      'noUsersFound': 'Không tìm thấy người dùng',
      'adminRole': 'Quản trị viên',
      'customerRole': 'Khách hàng',
      'orderManagement': 'Quản lý đơn hàng',
      'orderManagementSubtitle': 'Xem và cập nhật tất cả đơn hàng',
      'productManagement': 'Quản lý sản phẩm',
      'productInventory': 'Sản phẩm & tồn kho',
      'catalogInventory': 'Danh mục và tồn kho',
      'deleteProduct': 'Xóa sản phẩm',
      'deleteProductQuestion': 'Bạn có chắc muốn xóa',
      'productDeleted': 'Đã xóa sản phẩm thành công',
      'noCategory': 'Chưa có danh mục',
      'active': 'Đang hoạt động',
      'inactive': 'Ngừng hoạt động',
      'manageImages': 'Quản lý ảnh',
      'manageVariants': 'Quản lý biến thể',
      'editProduct': 'Sửa sản phẩm',
      'createProduct': 'Tạo sản phẩm',
      'updateProduct': 'Cập nhật sản phẩm',
      'productName': 'Tên sản phẩm',
      'basePrice': 'Giá gốc',
      'brand': 'Thương hiệu',
      'material': 'Chất liệu',
      'productCreated': 'Đã tạo sản phẩm thành công',
      'productUpdated': 'Đã cập nhật sản phẩm thành công',
      'failedLoadCategories': 'Không tải được danh mục',
      'invalidBasePrice': 'Giá gốc phải là số hợp lệ',
      'categoryManagement': 'Quản lý danh mục',
      'approveReturns': 'Duyệt trả hàng và hoàn tất hoàn tiền',
      'approveReturn': 'Duyệt yêu cầu trả hàng',
      'rejectReturn': 'Từ chối yêu cầu trả hàng',
      'completeRefundTransactionCode': 'Hoàn tất hoàn tiền: mã giao dịch',
      'returnRequests': 'Yêu cầu trả hàng',
      'refunds': 'Hoàn tiền',
      'returnRequest': 'Yêu cầu trả hàng',
      'refund': 'Hoàn tiền',
      'reject': 'Từ chối',
      'approve': 'Duyệt',
      'complete': 'Hoàn tất',
      'refundsEmpty': 'Chưa có giao dịch hoàn tiền.',
      'shipments': 'Vận chuyển',
      'shipment': 'Đơn vận chuyển',
      'noShipmentsFound': 'Không tìm thấy đơn vận chuyển',
      'searchShipments': 'Tìm đơn vận chuyển...',
      'adminAccessRequired': 'Cần quyền quản trị',
      'shipmentDetail': 'Chi tiết vận chuyển',
      'shipmentIdMissing': 'Thiếu mã đơn vận chuyển',
      'shipmentNotFound': 'Không tìm thấy đơn vận chuyển',
      'noNextStatus': 'Không có trạng thái tiếp theo hợp lệ',
      'noteOptional': 'Ghi chú (không bắt buộc)',
      'shipmentStatusUpdated': 'Đã cập nhật trạng thái vận chuyển thành',
      'orderInfo': 'Thông tin đơn hàng',
      'customerInfo': 'Thông tin khách hàng',
      'transactionCode': 'Mã giao dịch',
      'orderItems': 'Sản phẩm trong đơn',
      'noOrderItems': 'Không có sản phẩm trong đơn',
      'updateTrackingInfo': 'Cập nhật vận đơn',
      'updateShipmentStatus': 'Cập nhật trạng thái vận chuyển',
      'shipmentManagement': 'Quản lý vận chuyển',
      'shipmentManagementSubtitle': 'Tạo và theo dõi đơn vận chuyển',
      'deleteCategory': 'Xóa danh mục',
      'deleteCategoryQuestion': 'Bạn có chắc muốn xóa',
      'categoryDeleted': 'Đã xóa danh mục thành công',
      'editCategory': 'Sửa danh mục',
      'createCategory': 'Tạo danh mục',
      'updateCategory': 'Cập nhật danh mục',
      'categoryName': 'Tên danh mục',
      'categoryCreated': 'Đã tạo danh mục thành công',
      'categoryUpdated': 'Đã cập nhật danh mục thành công',
      'categoryNameTooLong': 'Tên danh mục phải dưới 100 ký tự',
      'descriptionTooLong': 'Mô tả phải dưới 255 ký tự',
      'createShipment': 'Tạo đơn vận chuyển',
      'shipmentSaved': 'Đã lưu đơn vận chuyển',
      'trackingUpdated': 'Đã cập nhật thông tin vận đơn',
      'orderId': 'Mã đơn hàng',
      'orderIdRequired': 'Vui lòng nhập mã đơn hàng',
      'carrierRequired': 'Vui lòng nhập đơn vị vận chuyển',
      'trackingNumberRequired': 'Vui lòng nhập mã vận đơn',
      'optionalDateFormat': 'Không bắt buộc, định dạng: YYYY-MM-DD',
      'saveChanges': 'Lưu thay đổi',
      'newSeason': 'Mùa mới / 2026',
      'heroTitle': 'Bạn làm\nđược.',
      'heroSubtitle':
          'Tự tin trong từng bước chân với giày dành cho thể thao, đường phố và mọi hành trình.',
      'shopNow': 'Mua ngay',
      'shopBySport': 'Mua theo môn thể thao',
      'viewAll': 'Xem tất cả',
      'trendingNow': 'Đang thịnh hành',
      'shopAll': 'Xem tất cả',
      'noProducts': 'Chưa có sản phẩm',
      'joinTheClub': 'Tham gia câu lạc bộ',
      'memberBenefits':
          'Thành viên nhận ưu đãi, sản phẩm mới và giao hàng miễn phí.',
      'becomeMember': 'Trở thành\nthành viên.',
      'registerSubtitle':
          'Tạo tài khoản để mở khóa sản phẩm, ưu đãi và trải nghiệm dành riêng cho thành viên.',
      'fullName': 'Họ và tên',
      'phoneOptional': 'Số điện thoại (không bắt buộc)',
      'acceptTerms':
          'Tôi đồng ý với điều khoản thành viên và chính sách riêng tư.',
      'creating': 'Đang tạo...',
      'createAccount': 'Tạo tài khoản',
      'alreadyMember': 'Đã là thành viên? Đăng nhập',
      'registerValidation':
          'Nhập họ tên, email và mật khẩu có ít nhất 6 ký tự.',
      'categories': 'Danh mục',
      'noCategories': 'Chưa có danh mục',
      'noDescription': 'Chưa có mô tả',
      'selectCategory': 'Chọn danh mục để xem sản phẩm',
      'noProductsIn': 'Không có sản phẩm trong',
      'error': 'Lỗi',
      'myCart': 'Giỏ hàng của tôi',
      'clearCart': 'Xóa giỏ hàng',
      'clearCartQuestion': 'Xóa tất cả sản phẩm khỏi giỏ hàng?',
      'clear': 'Xóa',
      'cartEmpty': 'Giỏ hàng đang trống',
      'total': 'Tổng cộng',
      'checkout': 'Thanh toán',
      'myWishlist': 'Danh sách yêu thích',
      'clearWishlist': 'Xóa danh sách yêu thích',
      'clearWishlistQuestion': 'Xóa tất cả sản phẩm yêu thích?',
      'wishlistEmpty': 'Danh sách yêu thích đang trống',
      'all': 'Tất cả',
      'searchHint': 'Tìm giày, bộ sưu tập, môn thể thao...',
      'noProductsFound': 'Không tìm thấy sản phẩm',
      'productDetails': 'Chi tiết sản phẩm',
      'noVariants': 'Chưa có biến thể',
      'selectSizeColor': 'Chọn kích cỡ & màu sắc',
      'selectSizeColorPrompt': 'Vui lòng chọn kích cỡ và màu sắc',
      'addedToCart': 'Đã thêm vào giỏ hàng',
      'addedToWishlist': 'Đã thêm vào yêu thích',
      'items': 'sản phẩm',
      'customerReviews': 'Đánh giá của khách hàng',
      'writeReview': 'Viết đánh giá',
      'editReview': 'Sửa đánh giá',
      'reviewLocked': 'Đã đánh giá',
      'noReviews':
          'Chưa có đánh giá. Hãy là người đầu tiên chia sẻ trải nghiệm.',
      'reviewSubmitted': 'Đã gửi đánh giá',
      'relatedProducts': 'Sản phẩm liên quan',
      'stock': 'Tồn kho',
      'productDescription': 'Mô tả sản phẩm',
      'productColor': 'Màu sắc',
      'productSize': 'Size',
      'addToBag': 'Thêm vào giỏ',
      'buyNow': 'Mua ngay',
      'adding': 'Đang thêm...',
      'shippingAddress': 'Địa chỉ giao hàng',
      'selectAddress': 'Chọn địa chỉ',
      'changeAddress': 'Đổi',
      'selectShippingAddress': 'Vui lòng chọn địa chỉ giao hàng',
      'orderCreated': 'Tạo đơn hàng thành công',
      'addShippingAddress': 'Thêm địa chỉ giao hàng',
      'paymentMethod': 'Phương thức thanh toán',
      'note': 'Ghi chú',
      'placeOrder': 'Đặt hàng',
      'vnpayUnavailable': 'Tích hợp VNPay chưa khả dụng',
      'cannotOpenVnpay': 'Không thể mở trang thanh toán VNPay',
      'orderCode': 'Mã đơn hàng',
      'orderStatus': 'Trạng thái',
      'payment': 'Thanh toán',
      'createdAt': 'Ngày tạo',
      'orderDetail': 'Chi tiết đơn hàng',
      'receiver': 'Người nhận',
      'name': 'Tên',
      'address': 'Địa chỉ',
      'quantity': 'Số lượng',
      'unitPrice': 'Đơn giá',
      'shipping': 'Vận chuyển',
      'shipmentUnavailable': 'Chưa có thông tin vận chuyển.',
      'trackShipment': 'Theo dõi vận chuyển',
      'shipmentStatus': 'Trạng thái vận chuyển',
      'carrier': 'Đơn vị vận chuyển',
      'trackingNumber': 'Mã vận đơn',
      'estimatedDelivery': 'Dự kiến giao',
      'shippedAt': 'Ngày gửi hàng',
      'deliveredAt': 'Ngày giao hàng',
      'receiverPhone': 'SĐT người nhận',
      'paymentStatus': 'Trạng thái thanh toán',
      'paidAt': 'Đã thanh toán lúc',
      'totals': 'Tổng tiền',
      'totalAmount': 'Tạm tính',
      'shippingFee': 'Phí vận chuyển',
      'discount': 'Giảm giá',
      'finalAmount': 'Thành tiền',
      'refreshPaymentStatus': 'Cập nhật thanh toán',
      'requestReturn': 'Yêu cầu trả hàng',
      'cancelOrder': 'Hủy đơn hàng',
      'cancelOrderQuestion': 'Hủy đơn hàng',
      'orderCancelled': 'Đã hủy đơn hàng thành công',
      'confirmReceived': 'Đã nhận hàng',
      'confirmReceivedMessage':
          'Xác nhận bạn đã nhận được đơn hàng và muốn hoàn tất đơn?',
      'orderCompleted':
          'Đơn hàng đã hoàn tất. Bạn có thể đánh giá sản phẩm đã mua.',
      'shipmentFallback':
          'Chưa có mã vận chuyển chi tiết. Bạn vẫn có thể theo dõi tiến trình theo trạng thái đơn hàng bên dưới.',
      'paymentStatusRefreshed': 'Đã cập nhật trạng thái thanh toán',
      'orderIdMissing': 'Thiếu mã đơn hàng',
      'orderNotFound': 'Không tìm thấy đơn hàng',
      'goToLogin': 'Đến đăng nhập',
      'noOrdersYet': 'Chưa có đơn hàng',
      'returnWholeOrder': 'Trả toàn bộ đơn hàng',
      'openReturnFromOrder': 'Vui lòng mở màn hình này từ chi tiết đơn hàng.',
      'returnReason': 'Lý do trả hàng',
      'returnReasonDefective': 'Hàng bị lỗi',
      'returnReasonWrongDescription': 'Hàng không đúng mô tả',
      'returnReasonWrongItem': 'Giao sai sản phẩm',
      'returnReasonMissingItem': 'Thiếu sản phẩm/phụ kiện',
      'returnReasonDamagedPackage': 'Kiện hàng bị móp/vỡ/hư hỏng',
      'returnReasonChangedMind': 'Không còn nhu cầu',
      'returnReasonOther': 'Lý do khác',
      'returnDetails': 'Mô tả thêm',
      'returnDetailsOptional': 'Mô tả thêm (không bắt buộc)',
      'returnEvidence': 'Ảnh/video bằng chứng',
      'returnEvidenceHint': 'Tải ảnh hoặc video lên làm bằng chứng',
      'choosePhotos': 'Chọn ảnh',
      'takePhoto': 'Chụp ảnh',
      'chooseVideo': 'Chọn video',
      'selectReturnReasonPrompt': 'Vui lòng chọn lý do trả hàng.',
      'returnSubmitted': 'Đã gửi yêu cầu trả hàng.',
      'submitReturnRequest': 'Gửi yêu cầu trả hàng',
      'submitting': 'Đang gửi...',
      'trackingProgress': 'Tiến trình vận chuyển',
      'order': 'Đơn hàng',
      'amount': 'Số tiền',
      'paymentResultHint':
          'Sau khi thanh toán, quay lại ứng dụng và cập nhật trạng thái thanh toán.',
      'paymentCompleted': 'Thanh toán thành công.',
      'viewOrderDetail': 'Xem chi tiết đơn hàng',
      'returnsRefundsEmpty': 'Chưa có yêu cầu trả hàng.',
      'adminNote': 'Ghi chú quản trị',
      'statusPending': 'Đang chờ',
      'statusApproved': 'Đã duyệt',
      'statusRefunded': 'Đã hoàn tiền',
      'statusRejected': 'Đã từ chối',
      'statusPreparing': 'Đang chuẩn bị',
      'statusShipped': 'Đã gửi hàng',
      'statusInTransit': 'Đang vận chuyển',
      'statusOutForDelivery': 'Đang giao tới bạn',
      'statusFailed': 'Giao thất bại',
      'statusReturned': 'Đã hoàn về',
    },
  };

  static String get(BuildContext context, String key) {
    final languageCode = AppLanguageScope.of(context).locale.languageCode;
    return _values[languageCode]?[key] ?? _values['en']![key] ?? key;
  }
}

extension AppTextContext on BuildContext {
  String tr(String key) => AppText.get(this, key);
}
