import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class AppLocaleController extends ChangeNotifier {
  AppLocaleController._();

  static final instance = AppLocaleController._();
  static const _preferenceKey = 'app_language';

  Locale _locale = const Locale('en');

  Locale get locale => _locale;
  bool get isVietnamese => _locale.languageCode == 'vi';

  Future<void> load() async {
    final preferences = await SharedPreferences.getInstance();
    _locale = Locale(preferences.getString(_preferenceKey) ?? 'en');
  }

  Future<void> setLanguage(String languageCode) async {
    if (_locale.languageCode == languageCode) return;
    _locale = Locale(languageCode);
    notifyListeners();
    final preferences = await SharedPreferences.getInstance();
    await preferences.setString(_preferenceKey, languageCode);
  }
}

class AppLanguageScope extends InheritedNotifier<AppLocaleController> {
  AppLanguageScope({
    super.key,
    required super.child,
  }) : super(notifier: AppLocaleController.instance);

  static AppLocaleController of(BuildContext context) {
    return context
        .dependOnInheritedWidgetOfExactType<AppLanguageScope>()!
        .notifier!;
  }
}

abstract final class AppText {
  static const Map<String, Map<String, String>> _values = {
    'en': {
      'settings': 'Settings',
      'language': 'Language',
      'languageSubtitle': 'Choose the language used in the app',
      'english': 'English',
      'vietnamese': 'Vietnamese',
      'myAccount': 'My account',
      'myOrders': 'My orders',
      'myOrdersSubtitle': 'Track, return or buy again',
      'returnsRefunds': 'Returns & refunds',
      'returnsRefundsSubtitle': 'Track return requests and refunds',
      'wishlist': 'Wishlist',
      'wishlistSubtitle': 'Your saved products',
      'addresses': 'Addresses',
      'addressesSubtitle': 'Manage delivery addresses',
      'changePassword': 'Change password',
      'changePasswordSubtitle': 'Update your account password',
      'helpSupport': 'Help & support',
      'helpSupportSubtitle': 'Returns, payments and contact',
      'signOut': 'Sign out',
      'forgotPassword': 'Forgot password?',
      'welcomeBack': 'Welcome\nback.',
      'signInSubtitle':
          'Sign in to access your bag, wishlist and member rewards.',
      'password': 'Password',
      'signIn': 'Sign in',
      'or': 'Or',
      'continueWithGoogle': 'Continue with Google',
      'notMember': 'Not a member?',
      'joinNow': 'Join now',
      'forgotPasswordTitle': 'Forgot password',
      'checkEmail': 'Check your\nemail.',
      'otpDescription':
          'We will send a 6-digit verification code to the email you enter.',
      'emailAddress': 'Email address',
      'sendOtp': 'Send OTP',
      'sending': 'Sending...',
      'otpSent': 'OTP was sent to',
      'resetPassword': 'Reset password',
      'verifyReset': 'Verify and\nreset.',
      'otpSentDescription': 'Enter the 6-digit OTP sent to',
      'otpExpires': 'It expires in 5 minutes.',
      'otpLabel': '6-digit OTP',
      'newPassword': 'New password',
      'confirmNewPassword': 'Confirm new password',
      'resetting': 'Resetting...',
      'resendOtp': 'Resend OTP',
      'otpResent': 'A new OTP has been sent.',
      'passwordResetSuccess': 'Password reset successfully.',
      'currentPassword': 'Current password',
      'changePasswordHeading': 'Secure your\naccount.',
      'passwordHint': 'Choose a new password with at least 6 characters.',
      'updating': 'Updating...',
      'passwordChanged': 'Password changed successfully.',
      'passwordLengthError': 'Password must contain at least 6 characters.',
      'passwordMismatch': 'New passwords do not match.',
      'myAddresses': 'My addresses',
      'addAddress': 'Add address',
      'editAddress': 'Edit address',
      'newDeliveryAddress': 'New delivery\naddress.',
      'updateAddress': 'Update your\naddress.',
      'saveAddress': 'Save address',
      'saving': 'Saving...',
      'defaultLabel': 'Default',
      'setDefault': 'Set default',
      'edit': 'Edit',
      'delete': 'Delete',
      'cancel': 'Cancel',
      'noAddresses': 'No saved addresses',
      'noAddressesSubtitle':
          'Add a delivery address to make checkout faster.',
      'addFirstAddress': 'Add your first address',
      'receiverName': 'Receiver name',
      'phoneNumber': 'Phone number',
      'streetAddress': 'Street address',
      'ward': 'Ward',
      'district': 'District',
      'cityProvince': 'City / Province',
      'setDefaultAddress': 'Set as default address',
      'setDefaultAddressSubtitle':
          'This address will be selected first at checkout.',
      'requiredField': 'Required field',
      'invalidEmail': 'Enter a valid email address.',
      'invalidPhone': 'Enter a valid phone number',
      'deleteAddressQuestion': 'Delete address?',
      'retry': 'Retry',
      'home': 'Home',
      'shop': 'Shop',
      'aiStylist': 'AI Stylist',
      'profile': 'Profile',
      'signInToContinue': 'Sign in to access your account features.',
      'register': 'Register',
      'adiclubMember': 'Adiclub member',
      'signInToSync': 'Sign in to sync your account',
      'adminTools': 'Admin tools',
      'adminDashboard': 'Admin dashboard',
      'businessOverview': 'Business overview',
      'orderManagement': 'Order management',
      'orderManagementSubtitle': 'Review and update all orders',
      'productManagement': 'Product management',
      'catalogInventory': 'Catalog and inventory',
      'approveReturns': 'Approve returns and complete refunds',
      'shipmentManagement': 'Shipment management',
      'shipmentManagementSubtitle': 'Create and track shipments',
      'newSeason': 'New season / 2026',
      'heroTitle': 'You got\nthis.',
      'heroSubtitle':
          'Own every move with footwear built for sport, streets and everything between.',
      'shopNow': 'Shop now',
      'shopBySport': 'Shop by sport',
      'viewAll': 'View all',
      'trendingNow': 'Trending now',
      'shopAll': 'Shop all',
      'noProducts': 'No products available',
      'joinTheClub': 'Join the club',
      'memberBenefits': 'Members get rewards, drops and free delivery.',
      'becomeMember': 'Become a\nmember.',
      'registerSubtitle':
          'Create your account and unlock members-only products, rewards and experiences.',
      'fullName': 'Full name',
      'phoneOptional': 'Phone number (optional)',
      'acceptTerms': 'I agree to the membership terms and privacy policy.',
      'creating': 'Creating...',
      'createAccount': 'Create account',
      'alreadyMember': 'Already a member? Sign in',
      'registerValidation':
          'Enter your name, email and a 6+ character password.',
      'categories': 'Categories',
      'noCategories': 'No categories found',
      'noDescription': 'No description',
      'selectCategory': 'Select a category to view products',
      'noProductsIn': 'No products in',
      'error': 'Error',
      'myCart': 'My cart',
      'clearCart': 'Clear cart',
      'clearCartQuestion': 'Remove all items from your cart?',
      'clear': 'Clear',
      'cartEmpty': 'Your cart is empty',
      'total': 'Total',
      'checkout': 'Checkout',
      'myWishlist': 'My wishlist',
      'clearWishlist': 'Clear wishlist',
      'clearWishlistQuestion': 'Remove all items from your wishlist?',
      'wishlistEmpty': 'Your wishlist is empty',
      'all': 'All',
      'searchHint': 'Search shoes, collections, sport...',
      'noProductsFound': 'No products found',
      'productDetails': 'Product details',
      'noVariants': 'No variants available',
      'selectSizeColor': 'Select size & color',
      'selectSizeColorPrompt': 'Please select size and color',
      'addedToCart': 'Added to cart',
      'addedToWishlist': 'Added to wishlist',
      'items': 'items',
      'customerReviews': 'Customer reviews',
      'writeReview': 'Write a review',
      'noReviews': 'No reviews yet. Be the first to share your experience.',
      'stock': 'Stock',
      'productDescription': 'Product description',
      'addToBag': 'Add to bag',
      'adding': 'Adding...',
      'shippingAddress': 'Shipping address',
      'selectShippingAddress': 'Please select a shipping address',
      'orderCreated': 'Order created successfully',
      'addShippingAddress': 'Add a shipping address',
      'paymentMethod': 'Payment method',
      'note': 'Note',
      'placeOrder': 'Place order',
      'vnpayUnavailable': 'VNPay integration is not available yet',
      'cannotOpenVnpay': 'Could not open VNPay payment page',
    },
    'vi': {
      'settings': 'Cài đặt',
      'language': 'Ngôn ngữ',
      'languageSubtitle': 'Chọn ngôn ngữ hiển thị trong ứng dụng',
      'english': 'Tiếng Anh',
      'vietnamese': 'Tiếng Việt',
      'myAccount': 'Tài khoản của tôi',
      'myOrders': 'Đơn hàng của tôi',
      'myOrdersSubtitle': 'Theo dõi, hoàn trả hoặc mua lại',
      'returnsRefunds': 'Trả hàng & hoàn tiền',
      'returnsRefundsSubtitle': 'Theo dõi yêu cầu trả hàng và hoàn tiền',
      'wishlist': 'Danh sách yêu thích',
      'wishlistSubtitle': 'Các sản phẩm bạn đã lưu',
      'addresses': 'Địa chỉ',
      'addressesSubtitle': 'Quản lý địa chỉ giao hàng',
      'changePassword': 'Đổi mật khẩu',
      'changePasswordSubtitle': 'Cập nhật mật khẩu tài khoản',
      'helpSupport': 'Trợ giúp & hỗ trợ',
      'helpSupportSubtitle': 'Trả hàng, thanh toán và liên hệ',
      'signOut': 'Đăng xuất',
      'forgotPassword': 'Quên mật khẩu?',
      'welcomeBack': 'Chào mừng\ntrở lại.',
      'signInSubtitle':
          'Đăng nhập để truy cập giỏ hàng, yêu thích và phần thưởng.',
      'password': 'Mật khẩu',
      'signIn': 'Đăng nhập',
      'or': 'Hoặc',
      'continueWithGoogle': 'Tiếp tục với Google',
      'notMember': 'Chưa có tài khoản?',
      'joinNow': 'Đăng ký ngay',
      'forgotPasswordTitle': 'Quên mật khẩu',
      'checkEmail': 'Kiểm tra\nemail.',
      'otpDescription': 'Chúng tôi sẽ gửi mã OTP 6 số tới email bạn nhập.',
      'emailAddress': 'Địa chỉ email',
      'sendOtp': 'Gửi OTP',
      'sending': 'Đang gửi...',
      'otpSent': 'OTP đã được gửi tới',
      'resetPassword': 'Đặt lại mật khẩu',
      'verifyReset': 'Xác thực và\nđặt lại.',
      'otpSentDescription': 'Nhập mã OTP 6 số đã gửi tới',
      'otpExpires': 'Mã hết hạn sau 5 phút.',
      'otpLabel': 'OTP 6 số',
      'newPassword': 'Mật khẩu mới',
      'confirmNewPassword': 'Xác nhận mật khẩu mới',
      'resetting': 'Đang đặt lại...',
      'resendOtp': 'Gửi lại OTP',
      'otpResent': 'OTP mới đã được gửi.',
      'passwordResetSuccess': 'Đặt lại mật khẩu thành công.',
      'currentPassword': 'Mật khẩu hiện tại',
      'changePasswordHeading': 'Bảo vệ\ntài khoản.',
      'passwordHint': 'Chọn mật khẩu mới có ít nhất 6 ký tự.',
      'updating': 'Đang cập nhật...',
      'passwordChanged': 'Đổi mật khẩu thành công.',
      'passwordLengthError': 'Mật khẩu phải có ít nhất 6 ký tự.',
      'passwordMismatch': 'Mật khẩu mới không khớp.',
      'myAddresses': 'Địa chỉ của tôi',
      'addAddress': 'Thêm địa chỉ',
      'editAddress': 'Sửa địa chỉ',
      'newDeliveryAddress': 'Địa chỉ giao\nhàng mới.',
      'updateAddress': 'Cập nhật\nđịa chỉ.',
      'saveAddress': 'Lưu địa chỉ',
      'saving': 'Đang lưu...',
      'defaultLabel': 'Mặc định',
      'setDefault': 'Đặt mặc định',
      'edit': 'Sửa',
      'delete': 'Xóa',
      'cancel': 'Hủy',
      'noAddresses': 'Chưa có địa chỉ',
      'noAddressesSubtitle':
          'Thêm địa chỉ giao hàng để thanh toán nhanh hơn.',
      'addFirstAddress': 'Thêm địa chỉ đầu tiên',
      'receiverName': 'Tên người nhận',
      'phoneNumber': 'Số điện thoại',
      'streetAddress': 'Địa chỉ đường',
      'ward': 'Phường / Xã',
      'district': 'Quận / Huyện',
      'cityProvince': 'Tỉnh / Thành phố',
      'setDefaultAddress': 'Đặt làm địa chỉ mặc định',
      'setDefaultAddressSubtitle':
          'Địa chỉ này sẽ được chọn trước khi thanh toán.',
      'requiredField': 'Trường bắt buộc',
      'invalidEmail': 'Vui lòng nhập email hợp lệ.',
      'invalidPhone': 'Vui lòng nhập số điện thoại hợp lệ',
      'deleteAddressQuestion': 'Xóa địa chỉ?',
      'retry': 'Thử lại',
      'home': 'Trang chủ',
      'shop': 'Cửa hàng',
      'aiStylist': 'Trợ lý AI',
      'profile': 'Tài khoản',
      'signInToContinue': 'Đăng nhập để sử dụng các chức năng tài khoản.',
      'register': 'Đăng ký',
      'adiclubMember': 'Thành viên Adiclub',
      'signInToSync': 'Đăng nhập để đồng bộ tài khoản',
      'adminTools': 'Công cụ quản trị',
      'adminDashboard': 'Bảng điều khiển quản trị',
      'businessOverview': 'Tổng quan hoạt động kinh doanh',
      'orderManagement': 'Quản lý đơn hàng',
      'orderManagementSubtitle': 'Xem và cập nhật tất cả đơn hàng',
      'productManagement': 'Quản lý sản phẩm',
      'catalogInventory': 'Danh mục và tồn kho',
      'approveReturns': 'Duyệt trả hàng và hoàn tất hoàn tiền',
      'shipmentManagement': 'Quản lý vận chuyển',
      'shipmentManagementSubtitle': 'Tạo và theo dõi đơn vận chuyển',
      'newSeason': 'Mùa mới / 2026',
      'heroTitle': 'Bạn làm\nđược.',
      'heroSubtitle':
          'Tự tin trong từng bước chân với giày dành cho thể thao, đường phố và mọi hành trình.',
      'shopNow': 'Mua ngay',
      'shopBySport': 'Mua theo môn thể thao',
      'viewAll': 'Xem tất cả',
      'trendingNow': 'Đang thịnh hành',
      'shopAll': 'Xem tất cả',
      'noProducts': 'Chưa có sản phẩm',
      'joinTheClub': 'Tham gia câu lạc bộ',
      'memberBenefits':
          'Thành viên nhận ưu đãi, sản phẩm mới và giao hàng miễn phí.',
      'becomeMember': 'Trở thành\nthành viên.',
      'registerSubtitle':
          'Tạo tài khoản để mở khóa sản phẩm, ưu đãi và trải nghiệm dành riêng cho thành viên.',
      'fullName': 'Họ và tên',
      'phoneOptional': 'Số điện thoại (không bắt buộc)',
      'acceptTerms': 'Tôi đồng ý với điều khoản thành viên và chính sách riêng tư.',
      'creating': 'Đang tạo...',
      'createAccount': 'Tạo tài khoản',
      'alreadyMember': 'Đã là thành viên? Đăng nhập',
      'registerValidation':
          'Nhập họ tên, email và mật khẩu có ít nhất 6 ký tự.',
      'categories': 'Danh mục',
      'noCategories': 'Chưa có danh mục',
      'noDescription': 'Chưa có mô tả',
      'selectCategory': 'Chọn danh mục để xem sản phẩm',
      'noProductsIn': 'Không có sản phẩm trong',
      'error': 'Lỗi',
      'myCart': 'Giỏ hàng của tôi',
      'clearCart': 'Xóa giỏ hàng',
      'clearCartQuestion': 'Xóa tất cả sản phẩm khỏi giỏ hàng?',
      'clear': 'Xóa',
      'cartEmpty': 'Giỏ hàng đang trống',
      'total': 'Tổng cộng',
      'checkout': 'Thanh toán',
      'myWishlist': 'Danh sách yêu thích',
      'clearWishlist': 'Xóa danh sách yêu thích',
      'clearWishlistQuestion': 'Xóa tất cả sản phẩm yêu thích?',
      'wishlistEmpty': 'Danh sách yêu thích đang trống',
      'all': 'Tất cả',
      'searchHint': 'Tìm giày, bộ sưu tập, môn thể thao...',
      'noProductsFound': 'Không tìm thấy sản phẩm',
      'productDetails': 'Chi tiết sản phẩm',
      'noVariants': 'Chưa có biến thể',
      'selectSizeColor': 'Chọn kích cỡ & màu sắc',
      'selectSizeColorPrompt': 'Vui lòng chọn kích cỡ và màu sắc',
      'addedToCart': 'Đã thêm vào giỏ hàng',
      'addedToWishlist': 'Đã thêm vào yêu thích',
      'items': 'sản phẩm',
      'customerReviews': 'Đánh giá của khách hàng',
      'writeReview': 'Viết đánh giá',
      'noReviews': 'Chưa có đánh giá. Hãy là người đầu tiên chia sẻ trải nghiệm.',
      'stock': 'Tồn kho',
      'productDescription': 'Mô tả sản phẩm',
      'addToBag': 'Thêm vào giỏ',
      'adding': 'Đang thêm...',
      'shippingAddress': 'Địa chỉ giao hàng',
      'selectShippingAddress': 'Vui lòng chọn địa chỉ giao hàng',
      'orderCreated': 'Tạo đơn hàng thành công',
      'addShippingAddress': 'Thêm địa chỉ giao hàng',
      'paymentMethod': 'Phương thức thanh toán',
      'note': 'Ghi chú',
      'placeOrder': 'Đặt hàng',
      'vnpayUnavailable': 'Tích hợp VNPay chưa khả dụng',
      'cannotOpenVnpay': 'Không thể mở trang thanh toán VNPay',
    },
  };

  static String get(BuildContext context, String key) {
    final languageCode = AppLanguageScope.of(context).locale.languageCode;
    return _values[languageCode]?[key] ?? _values['en']![key] ?? key;
  }
}

extension AppTextContext on BuildContext {
  String tr(String key) => AppText.get(this, key);
}
